project:
  type: website
  output-dir: docs

website:
  title: "Scott Burgert's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quantumech3
      - icon: linkedin
        href: https://www.linkedin.com/in/scott-burgert-0b27a1178/
      - icon: book
        href: https://drive.google.com/file/d/1WMX6dgyRZIXhpBw2kPpuSp5lAH2o9AY7/view?usp=sharing

format:
  html:
    theme: [cosmo, dark.scss]
    css: styles.css



