project:
  type: website
  output-dir: docs

website:
  title: "Scott Burgert's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quantumech3
      - icon: linkedin
        href: https://www.linkedin.com/in/scott-burgert-0b27a1178/
format:
  html:
    theme: cosmo
    css: styles.css



